animals = ['bear', 'python', 'peacock', 'kangaroo', 'whale', 'platypus']
print "The animal at 1 is %s." %animals[1]
print "The third animal is at 2 and is a %s." %animals[2]
print "The first animal is at 0 and is a %s." %animals[0]
print "The animal at 3 is %s." %animals[3]
print "The fifth animal is at 4 and is a %s." %animals[4]
print "The animal at 2 is %s." %animals[2]
print "The sixth animal is at 5 and is a %s." %animals[5]
print "The animal at 4 is a %s." %animals[4] 
